import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    brandName: "AgriMart",
    tagline: "India's #1 Farmer & Agriculture Marketplace",
    kisanHelpline: "Kisan Toll-Free Helpline: 1800-180-1551",
    freeDeliveryText: "Free Farm Gate Delivery on orders above ₹999",
    searchPlaceholder: "Search for seeds, fertilizers, sprayers, pesticides, or crops...",
    allCategories: "All Categories",
    sellHarvest: "Sell Your Harvest / Products",
    farmerPortal: "Farmer Portal",
    trackOrder: "Track Order",
    cropDoctor: "Crop Doctor (AI Advisory)",
    dosageCalc: "Fertilizer & Seed Calculator",
    wishlist: "Wishlist",
    cart: "Cart",
    items: "items",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    quickView: "Quick View",
    bestSeller: "Best Seller",
    govtCertified: "Govt Certified",
    organicCertified: "100% Organic",
    hotDeal: "Hot Deal",
    originalPrice: "M.R.P.",
    save: "Save",
    dosage: "Dosage & Usage",
    suitableFor: "Suitable For",
    manufacturer: "Manufacturer",
    reviews: "Reviews",
    filterBy: "Filter By",
    all: "All",
    organicOnly: "Organic / Bio Only",
    priceRange: "Price Range",
    sortBy: "Sort By",
    sortPopular: "Most Popular",
    sortPriceLow: "Price: Low to High",
    sortPriceHigh: "Price: High to Low",
    sortRating: "Highest Rated",
    checkDelivery: "Check Delivery Pincode",
    enterPincode: "Enter 6-digit Pincode",
    check: "Check",
    bulkDiscountAlert: "Buy in Bulk & Save up to 10% Extra!",
    emptyCartTitle: "Your Agri Cart is Empty",
    emptyCartSubtitle: "Explore our certified seeds, fertilizers, and farming tools to boost your crop yield.",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    discount: "Bulk Farmer Discount",
    deliveryFee: "Delivery Charges",
    free: "FREE",
    grandTotal: "Grand Total",
    proceedToCheckout: "Proceed to Checkout",
    orderSuccess: "Order Placed Successfully!",
    orderIdText: "Order ID",
    downloadInvoice: "Download Tax Invoice",
    trackMyOrder: "Track Live Delivery",
    continueShopping: "Continue Shopping",
    calculatorTitle: "Agri Fertilizer & Seed Rate Calculator",
    calculatorSubtitle: "Calculate precise seed requirements and NPK fertilizer dosage for your farmland to maximize yield and cut costs.",
    selectCrop: "Select Crop",
    enterAcreage: "Farm Land Area (in Acres)",
    calculateNow: "Calculate Requirement",
    addBundleToCart: "Add Complete Recommended Bundle to Cart",
    cropDoctorTitle: "Kisan Crop Doctor - Instant Disease Diagnostic",
    cropDoctorSubtitle: "Identify crop diseases, pest infestations, and get instant organic remedies and treatment products.",
    symptomsObserved: "Symptoms Observed",
    treatmentProtocol: "Recommended Treatment & Remedy",
    recommendedProducts: "Remedy Products Available in Store"
  },
  hi: {
    brandName: "एग्रीमार्ट",
    tagline: "भारत का #1 किसान और कृषि उत्पाद बाज़ार",
    kisanHelpline: "किसान टोल-फ्री हेल्पलाइन: 1800-180-1551",
    freeDeliveryText: "₹999 से अधिक के ऑर्डर पर सीधे खेत/घर तक निःशुल्क डिलीवरी",
    searchPlaceholder: "बीज, खाद, स्प्रेयर, कीटनाशक या फसल खोजें...",
    allCategories: "सभी श्रेणियां",
    sellHarvest: "अपनी फसल / उत्पाद बेचें",
    farmerPortal: "किसान पोर्टल",
    trackOrder: "ऑर्डर ट्रैक करें",
    cropDoctor: "फसल डॉक्टर (रोग निदान)",
    dosageCalc: "खाद व बीज दर कैलकुलेटर",
    wishlist: "पसंदीदा सूची",
    cart: "कार्ट",
    items: "सामान",
    inStock: "स्टॉक में उपलब्ध",
    outOfStock: "स्टॉक समाप्त",
    addToCart: "कार्ट में जोड़ें",
    buyNow: "अभी खरीदें",
    quickView: "विवरण देखें",
    bestSeller: "सर्वाधिक बिकने वाला",
    govtCertified: "सरकारी प्रमाणित",
    organicCertified: "100% जैविक",
    hotDeal: "खास ऑफर",
    originalPrice: "एम.आर.पी.",
    save: "बचत",
    dosage: "उपयोग विधि व मात्रा",
    suitableFor: "उपयुक्त फसलें",
    manufacturer: "निर्माता कंपनी",
    reviews: "समीक्षाएं",
    filterBy: "फ़िल्टर करें",
    all: "सभी",
    organicOnly: "केवल जैविक / बायो",
    priceRange: "मूल्य दायरा",
    sortBy: "क्रमबद्ध करें",
    sortPopular: "लोकप्रियता अनुसार",
    sortPriceLow: "कीमत: कम से ज्यादा",
    sortPriceHigh: "कीमत: ज्यादा से कम",
    sortRating: "उच्चतम रेटिंग",
    checkDelivery: "पिनकोड द्वारा डिलीवरी जांचें",
    enterPincode: "6-अंकों का पिनकोड दर्ज करें",
    check: "जांचें",
    bulkDiscountAlert: "थोक में खरीदें और 10% तक अतिरिक्त छूट पाएं!",
    emptyCartTitle: "आपकी कृषि कार्ट खाली है",
    emptyCartSubtitle: "अपनी उपज बढ़ाने के लिए हमारे प्रमाणित बीज, खाद और कृषि उपकरण देखें।",
    startShopping: "खरीदारी शुरू करें",
    subtotal: "उप-योग (Subtotal)",
    discount: "थोक किसान छूट",
    deliveryFee: "डिलीवरी शुल्क",
    free: "निःशुल्क (FREE)",
    grandTotal: "कुल देय राशि",
    proceedToCheckout: "चेकआउट करें",
    orderSuccess: "ऑर्डर सफलतापूर्वक दर्ज हुआ!",
    orderIdText: "ऑर्डर संख्या (Order ID)",
    downloadInvoice: "पक्का बिल (Invoice) डाउनलोड करें",
    trackMyOrder: "लाइव डिलीवरी ट्रैक करें",
    continueShopping: "खरीदारी जारी रखें",
    calculatorTitle: "कृषि खाद व बीज मात्रा कैलकुलेटर",
    calculatorSubtitle: "लागत घटाने और पैदावार बढ़ाने हेतु अपने खेत के रकबे अनुसार सटीक खाद व बीज की गणना करें।",
    selectCrop: "फसल चुनें",
    enterAcreage: "खेत का रकबा (एकड़ में)",
    calculateNow: "गणना करें",
    addBundleToCart: "अनुशंसित संपूर्ण किट कार्ट में जोड़ें",
    cropDoctorTitle: "किसान फसल डॉक्टर - त्वरित रोग निदान",
    cropDoctorSubtitle: "फसल के रोगों व कीटों की तुरंत पहचान करें और जैविक उपचार व सही दवाई प्राप्त करें।",
    symptomsObserved: "दिखाई देने वाले लक्षण",
    treatmentProtocol: "अनुशंसित उपचार और उपाय",
    recommendedProducts: "स्टोर में उपलब्ध उपचार उत्पाद"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
